<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net9.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Mana.Table.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Mana.Table/Mana.Table.csproj" /></ItemGroup>
</Project>
