<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>ManaTable</AssemblyName><ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <ProjectReference Include="../Mana.Forge/Mana.Forge.csproj" />
    <ProjectReference Include="../Mana.Client/Mana.Client.csproj" />
    <ProjectReference Include="../Mana.Magic/Mana.Magic.csproj" />
    <ProjectReference Include="../Mana.Renderer/Mana.Renderer.csproj" />
    <Content Include="Assets/**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
